server:
  port: 8080
  host: "0.0.0.0"

github:
  commit-url-list:
    - "https://api.github.com/repos/AnteUpLoser/gpt-picbed-01/contents/"
    - "https://api.github.com/repos/AnteUpLoser/gpt-picbed-02/contents/"
    - "https://api.github.com/repos/AnteUpLoser/gpt-picbed-03/contents/"
    - "https://api.github.com/repos/AnteUpLoser/gpt-picbed-04/contents/"
    - "https://api.github.com/repos/AnteUpLoser/gpt-picbed-05/contents/"
    - "https://api.github.com/repos/AnteUpLoser/gpt-picbed-06/contents/"
    - "https://api.github.com/repos/AnteUpLoser/gpt-picbed-07/contents/"
    - "https://api.github.com/repos/AnteUpLoser/gpt-picbed-08/contents/"
    - "https://api.github.com/repos/AnteUpLoser/gpt-picbed-09/contents/"
    - "https://api.github.com/repos/AnteUpLoser/gpt-picbed-10/contents/"
  
  authorization: "Bearer ghp_XXX"
  accept: "application/vnd.github+json"
  api-version: "2022-11-28" 